version: "3.8"
networks:
  mojaloop-net:
    name: mojaloop-net


services:
  mifos-core-connector:
    image: mojaloop/mifos-core-connector:latest
    build:
      context: .
    networks:
      - mojaloop-net
    env_file: .env.example
    ports:
      - "3003:3003"
      - "3004:3004"
