openapi: 3.0.3
info:
    title: Mifos Core Connector for Mojaloop SDK Scheme Adapter API
    version: 0.0.1
    description: >
        API Specification for the Mifos Core Connector from the SDK Scheme Adapter

        This API is to be implemented by the DFSP
    license:
        name: Apache License Version 2.0, January 2004
        url: http://www.apache.org/licenses/

paths:
    /parties/IBAN/{ID}:
        get:
            tags:
                - Get Parties
            summary: Perform Account Lookup in Fineract.
            description: Lookup a party from a remote fineract instance from IBAN
            operationId: getParties
            parameters:
                - name: ID
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: 'Return Party Information'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PartyInfo'
                '404':
                    description: 'Party with IBAN does not exist in fineract'
                '500':
                    description: 'Internal Server Error'

    /quoterequests:
        post:
            tags:
                - Quote Requests
            summary: Request a quote from fineract for a specified receiveTransfer
            description: Request a quote for a transaction in fineract
            operationId: quoteRequests
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/QuoteRequest'
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/QuoteResponse'
                    description: 'Successful Quote'
                '400':
                    description: 'Bad Request'
                '500':
                    description: 'Internal Server Error'

    /transfers:
        post:
            tags:
                - Transfer Request
            summary: Request to make a receiveTransfer from an account from a mojaloop scheme to a fineract account
            description: Request to make a receiveTransfer
            operationId: transfers
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TransferRequest'
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TransferResponse'
                    description: 'Successful receiveTransfer'
                '400':
                    description: 'Bad Request'
                '500':
                    description: 'Internal Server Error'

components:
    schemas:
        IdType:
            type: string
            enum:
                - MSISDN
                - ACCOUNT_NO
                - EMAIL
                - PERSONAL_ID
                - BUSINESS
                - DEVICE
                - ACCOUNT_ID
                - IBAN
                - ALIAS

        PartyInfo:
            type: object
            required:
                - idType
                - idValue
            properties:
                dateOfBirth:
                    type: string
                    example: '8477-05-21'
                displayName:
                    type: string
                extensionList:
                    type: array
                    items:
                        type: object
                        properties:
                            key:
                                type: string
                            value:
                                type: string
                firstName:
                    type: string
                    description: 'First Name'
                fspId:
                    type: string
                    description: 'FSP Id'
                idSubValue:
                    type: string
                    description: 'Id Sub Value'
                idType:
                    $ref: '#/components/schemas/IdType'
                idValue:
                    type: string
                    description: 'ID Value'
                lastName:
                    type: string
                merchantClassificationCode:
                    type: string
                middleName:
                    type: string
                type:
                    type: string
                supportedCurrencies:
                    type: array
                    items:
                        type: string
                kycInformation:
                    type: string

        QuoteRequest:
            type: object
            required:
                - amount
                - amountType
                - currency
                - from
                - initiator
                - initiatorType
                - quoteId
                - to
                - transactionId
                - transactionType
            properties:
                homeR2PTransactionId:
                    type: string
                    example: 'string'
                amount:
                    type: string
                    example: '100'
                amountType:
                    type: string
                    example: 'SEND'
                currency:
                    type: string
                    example: 'ZMW'
                expiration:
                    type: string
                    example: '3177-01-09T02:50:53.508-09:33'
                extensionList:
                    type: array
                    items:
                        type: object
                        properties:
                            key:
                                type: string
                            value:
                                type: string
                feesAmount:
                    type: string
                    example: '0'
                feesCurrency:
                    type: string
                    example: 'ZMW'
                from:
                    type: object
                    properties:
                        dateOfBirth:
                            type: string
                            example: '8477-05-21'
                        displayName:
                            type: string
                        extensionList:
                            type: array
                            items:
                                type: object
                                properties:
                                    key:
                                        type: string
                                    value:
                                        type: string
                        firstName:
                            type: string
                            description: 'First Name'
                        fspId:
                            type: string
                            description: 'FSP Id'
                        idSubValue:
                            type: string
                            description: 'Id Sub Value'
                        idType:
                            $ref: '#/components/schemas/IdType'
                        idValue:
                            type: string
                            description: 'ID Value'
                        lastName:
                            type: string
                        merchantClassificationCode:
                            type: string
                        middleName:
                            type: string
                        type:
                            type: string
                        supportedCurrencies:
                            type: array
                            items:
                                type: string
                        kycInformation:
                            type: string
                geoCode:
                    type: object
                    properties:
                        latitude:
                            type: string
                        longitude:
                            type: string
                initiator:
                    type: string
                    example: 'PAYER'
                initiatorType:
                    type: string
                    example: 'CONSUMER'
                note:
                    type: string
                quoteId:
                    type: string
                    example: 'c8fa8773-990c-44a0-9c55-e0b18db6f7e1'
                subScenario:
                    type: string
                to:
                    type: object
                    properties:
                        dateOfBirth:
                            type: string
                            example: '8477-05-21'
                        displayName:
                            type: string
                        extensionList:
                            type: array
                            items:
                                type: object
                                properties:
                                    key:
                                        type: string
                                    value:
                                        type: string
                        firstName:
                            type: string
                            description: 'First Name'
                        fspId:
                            type: string
                            description: 'FSP Id'
                        idSubValue:
                            type: string
                            description: 'Id Sub Value'
                        idType:
                            $ref: '#/components/schemas/IdType'
                        idValue:
                            type: string
                            description: 'ID Value'
                        lastName:
                            type: string
                        merchantClassificationCode:
                            type: string
                        middleName:
                            type: string
                        type:
                            type: string
                        supportedCurrencies:
                            type: array
                            items:
                                type: string
                        kycInformation:
                            type: string
                transactionId:
                    type: string
                    example: '7045667d-e774-304c-b550-c0bf3c3c69a1'
                transactionType:
                    type: string
                    example: 'TRANSFER'
                transactionRequestId:
                    type: string
                    example: '2d97299f-708a-1423-a36d-6df4187d513e'
                converter:
                    type: string
                    example: 'converter'
                currencyConversion:
                    type: string

        QuoteResponse:
            type: object
            properties:
                expiration:
                    type: string
                    example: '3945-08-30T22:03:24.190Z'
                extensionList:
                    type: array
                    items:
                        type: object
                        properties:
                            key:
                                type: string
                            value:
                                type: string
                geoCode:
                    type: object
                    properties:
                        latitude:
                            type: string
                        longitude:
                            type: string
                payeeFspCommissionAmount:
                    type: string
                    example: '72'
                payeeFspCommissionAmountCurrency:
                    type: string
                    example: 'AED'
                payeeFspFeeAmount:
                    type: string
                    example: '0'
                payeeFspFeeAmountCurrency:
                    type: string
                    example: 'AED'
                payeeReceiveAmount:
                    type: string
                    example: '0'
                payeeReceiveAmountCurrency:
                    type: string
                    example: 'AED'
                quoteId:
                    type: string
                    example: '71cee55f-c58a-2a8e-8289-e18a2c80bf48'
                transactionId:
                    type: string
                    example: '2861d780-60f5-5127-a73b-ab0617c00f72'
                transferAmount:
                    type: string
                    example: '0.9'
                transferAmountCurrency:
                    type: string
                    example: 'AED'

        TransferRequest:
            type: object
            required:
                - to
            properties:
                homeR2PTransactionId:
                    type: string
                    example: 'string'
                amount:
                    type: string
                    example: '0.347'
                amountType:
                    type: string
                    example: 'SEND'
                currency:
                    type: string
                    example: 'AED'
                from:
                    $ref: '#/components/schemas/PartyInfo'
                to:
                    $ref: '#/components/schemas/PartyInfo'
                ilpPacket:
                    type: object
                    properties:
                        data:
                            type: object
                            properties:
                                amount:
                                    type: object
                                    properties:
                                        amount:
                                            type: string
                                        currency:
                                            type: string
                                payee:
                                    type: object
                                    properties:
                                        partyIdInfo:
                                            type: object
                                            properties:
                                                partyIdType:
                                                    type: string
                                                partyIdentifier:
                                                    type: string
                                payer:
                                    type: object
                                    properties:
                                        partyIdInfo:
                                            type: object
                                            properties:
                                                partyIdType:
                                                    type: string
                                                partyIdentifier:
                                                    type: string
                                quoteId:
                                    type: string
                                transactionId:
                                    type: string
                                transactionType:
                                    type: object
                                    properties:
                                        initiator:
                                            type: string
                                        initiatorType:
                                            type: string
                                        scenario:
                                            type: string
                                        subScenario:
                                            type: string
                note:
                    type: string
                quote:
                    type: object
                    properties:
                        expiration:
                            type: string
                            example: '3945-08-30T22:03:24.190Z'
                        extensionList:
                            type: array
                            items:
                                type: object
                                properties:
                                    key:
                                        type: string
                                    value:
                                        type: string
                        geoCode:
                            type: object
                            properties:
                                latitude:
                                    type: string
                                longitude:
                                    type: string
                        payeeFspCommissionAmount:
                            type: string
                            example: '72'
                        payeeFspCommissionAmountCurrency:
                            type: string
                            example: 'AED'
                        payeeFspFeeAmount:
                            type: string
                            example: '0'
                        payeeFspFeeAmountCurrency:
                            type: string
                            example: 'AED'
                        payeeReceiveAmount:
                            type: string
                            example: '0'
                        payeeReceiveAmountCurrency:
                            type: string
                            example: 'AED'
                        quoteId:
                            type: string
                            example: '71cee55f-c58a-2a8e-8289-e18a2c80bf48'
                        transactionId:
                            type: string
                            example: '2861d780-60f5-5127-a73b-ab0617c00f72'
                        transferAmount:
                            type: string
                            example: '0.9'
                        transferAmountCurrency:
                            type: string
                            example: 'AED'
                quoteRequestExtensions:
                    type: array
                    items:
                        type: object
                        properties:
                            key:
                                type: string
                            value:
                                type: string
                subScenario:
                    type: string
                transactionType:
                    type: string
                transferId:
                    type: string
                transactionRequestId:
                    type: string

        TransferResponse:
            type: object
            properties:
                completedTimestamp:
                    type: string
                fulfilment:
                    type: string
                homeTransactionId:
                    type: string
                transferState:
                    type: string
